"""Policy-aware public page fetching and multi-tag evidence extraction."""

import html
import ipaddress
import re
import socket
from datetime import datetime
from html.parser import HTMLParser
from urllib.parse import urljoin, urlsplit
from urllib.robotparser import RobotFileParser

import requests
from django.conf import settings
from django.utils import timezone

from recommendations.services.evidence_scoring import evidence_confidence, parse_observed_date
from recommendations.services.naver_tag_evidence_provider import identity_assessment, polarity_assessment
from recommendations.services.web_tag_evidence_provider import CATEGORY_TAGS, canonical_url, is_blocked_source


ALLOWED_CONTENT_TYPES = ("text/html", "application/xhtml+xml")
BLOCKED_HOST_PARTS = ("map.naver.com", "m.place.naver.com", "place.map.kakao.com", "map.kakao.com", "google.com/maps", "maps.google.")
LOW_TRUST_AUTOGENERATED_HOSTS = (
    "place.udanax.org", "localmap.co.kr", "everyshoppos.com", "cokmap.com",
    "tastyhouse4u.tistory.com",
)
SENTENCE_SPLIT = re.compile(r"(?<=[.!?。]|[다요죠])\s+|[\r\n]+")
META_DATE_KEYS = {"article:published_time", "date", "datepublished", "pubdate", "publishdate"}
VOID_HTML_TAGS = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link", "meta", "param", "source", "track", "wbr"}
RELATED_SECTION_MARKERS = (
    "와 비슷한 맛집", "현 식당에서", "둘러볼만한 맛집 더보기",
    "주변 맛집", "근처 맛집", "함께 보면 좋은",
)


class PageTextParser(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.title = ""
        self.text = []
        self.main_text = []
        self.meta = {}
        self.frames = []
        self._ignored = 0
        self._in_title = False
        self._main_depth = 0

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        attrs = {str(key).lower(): value for key, value in attrs if key}
        if self._main_depth and tag not in VOID_HTML_TAGS:
            self._main_depth += 1
        elif tag == "div" and "se-main-container" in str(attrs.get("class") or "").split():
            self._main_depth = 1
        if tag in {"script", "style", "noscript", "svg", "canvas", "template"}:
            self._ignored += 1
        if tag == "title":
            self._in_title = True
        if tag == "meta":
            key = str(attrs.get("property") or attrs.get("name") or "").lower()
            value = str(attrs.get("content") or "").strip()
            if key and value:
                self.meta[key] = value
        if tag == "iframe" and attrs.get("src"):
            self.frames.append(str(attrs["src"]).strip())

    def handle_endtag(self, tag):
        tag = tag.lower()
        if tag in {"script", "style", "noscript", "svg", "canvas", "template"} and self._ignored:
            self._ignored -= 1
        if tag == "title":
            self._in_title = False
        if self._main_depth:
            self._main_depth -= 1

    def handle_data(self, data):
        if self._ignored:
            return
        value = re.sub(r"\s+", " ", html.unescape(str(data or ""))).strip()
        if not value:
            return
        if self._in_title:
            self.title = (self.title + " " + value).strip()
        self.text.append(value)
        if self._main_depth:
            self.main_text.append(value)


def safe_public_url(url):
    url = canonical_url(url)
    if not url or is_blocked_source(url):
        return "", "SOURCE_REJECT"
    parts = urlsplit(url)
    if parts.scheme not in {"http", "https"} or not parts.hostname:
        return "", "SOURCE_REJECT"
    if (
        parts.username or parts.password
        or any(part in parts.netloc.lower() for part in BLOCKED_HOST_PARTS)
        or any(parts.hostname == host or parts.hostname.endswith("." + host) for host in LOW_TRUST_AUTOGENERATED_HOSTS)
    ):
        return "", "SOURCE_REJECT"
    try:
        addresses = {row[4][0] for row in socket.getaddrinfo(parts.hostname, parts.port or 443)}
    except (OSError, socket.gaierror):
        return "", "DNS_FAILED"
    for address in addresses:
        ip = ipaddress.ip_address(address)
        if not ip.is_global:
            return "", "NON_PUBLIC_ADDRESS"
    return url, ""


def robots_allowed(url, *, session=None, cache=None):
    session = session or requests.Session()
    cache = cache if cache is not None else {}
    parts = urlsplit(url)
    origin = "{}://{}".format(parts.scheme, parts.netloc)
    if origin in cache:
        parser = cache[origin]
        return parser is not None and parser.can_fetch(_user_agent(), url)
    robots_url = origin + "/robots.txt"
    try:
        response = session.get(robots_url, headers={"User-Agent": _user_agent()}, timeout=_timeout(), allow_redirects=False)
    except requests.RequestException:
        cache[origin] = None
        return False
    if response.status_code == 404:
        parser = RobotFileParser()
        parser.set_url(robots_url)
        parser.parse([])
        cache[origin] = parser
        return True
    if response.status_code != 200:
        cache[origin] = None
        return False
    parser = RobotFileParser()
    parser.set_url(robots_url)
    parser.parse(response.text.splitlines())
    cache[origin] = parser
    return parser.can_fetch(_user_agent(), url)


def fetch_public_page(url, *, session=None, robots_cache=None):
    session = session or requests.Session()
    current, error = safe_public_url(url)
    if error:
        return _fetch_result(error=error)
    for _ in range(4):
        if not robots_allowed(current, session=session, cache=robots_cache):
            return _fetch_result(error="ROBOTS_REJECT")
        try:
            response = session.get(
                current,
                headers={"User-Agent": _user_agent(), "Accept": "text/html,application/xhtml+xml"},
                timeout=_timeout(),
                allow_redirects=False,
                stream=True,
            )
        except requests.RequestException:
            return _fetch_result(error="FETCH_FAILED")
        if response.status_code in {301, 302, 303, 307, 308}:
            target, error = safe_public_url(urljoin(current, response.headers.get("Location") or ""))
            if error:
                return _fetch_result(error=error)
            current = target
            continue
        if response.status_code == 429:
            return _fetch_result(error="RATE_LIMITED", status_code=429)
        if response.status_code != 200:
            return _fetch_result(error="HTTP_{}".format(response.status_code), status_code=response.status_code)
        content_type = str(response.headers.get("Content-Type") or "").split(";", 1)[0].lower()
        if content_type not in ALLOWED_CONTENT_TYPES:
            return _fetch_result(error="CONTENT_TYPE_REJECT", status_code=200, content_type=content_type)
        maximum = _max_bytes()
        chunks = []
        size = 0
        for chunk in response.iter_content(16384):
            size += len(chunk)
            if size > maximum:
                return _fetch_result(error="BODY_TOO_LARGE", status_code=200, content_type=content_type)
            chunks.append(chunk)
        encoding = response.encoding or "utf-8"
        body = b"".join(chunks).decode(encoding, errors="replace")
        parser = PageTextParser()
        try:
            parser.feed(body)
        except (ValueError, AssertionError):
            return _fetch_result(error="HTML_PARSE_FAILED", status_code=200, content_type=content_type)
        all_text = re.sub(r"\s+", " ", " ".join(parser.text)).strip()
        main_text = re.sub(r"\s+", " ", " ".join(parser.main_text)).strip()
        text = main_text if main_text else all_text
        if len(text) < _min_text_length():
            frame_url = _public_post_frame(current, parser.frames)
            if frame_url:
                current = frame_url
                continue
            return _fetch_result(error="BODY_TOO_SHORT", status_code=200, content_type=content_type)
        return {
            "ok": True, "error": "", "url": canonical_url(current), "title": parser.title[:300],
            "text": text[:_max_text_length()], "published_at": _published_at(parser.meta),
            "content_type": content_type, "status_code": 200, "bytes": size,
        }
    return _fetch_result(error="TOO_MANY_REDIRECTS")


def extract_page_evidences(place, page, *, query="", result_rank=0):
    title = str(page.get("title") or "")
    text = relevant_page_text(str(page.get("text") or ""))
    identity = identity_assessment(place, "{} {}".format(title, text), title=title)
    exact_title = _compact(place.name) in _compact(title)
    identity["page_title_exact"] = exact_title
    identity["matched"] = bool(identity["matched"] and exact_title and identity["score"] >= 80)
    if not identity["matched"]:
        return {"identity": identity, "evidences": [], "error": "IDENTITY_MISMATCH"}
    observed_at = parse_observed_date(page.get("published_at"))
    evidences = []
    for tag_name in CATEGORY_TAGS.get(place.category, ()):
        extraction = polarity_assessment(tag_name, text, category=place.category)
        if extraction["polarity"] not in {"positive", "negative"}:
            continue
        span = evidence_span(text, extraction)
        if not span:
            continue
        extraction = normalize_page_polarity(tag_name, span, extraction)
        if extraction["polarity"] == "positive" and tag_name == "조용함":
            compact_span = _compact(span)
            quiet_context = ("조용한분위기", "조용하고", "조용해서", "한적", "차분한분위기", "차분한공간", "북적이지", "시끄럽지", "공간", "매장", "카페")
            if not any(_compact(term) in compact_span for term in quiet_context):
                continue
        if extraction["polarity"] == "positive" and tag_name == "장기체류좋음":
            compact_span = _compact(span)
            stay_context = ("오래머물", "오래있", "오래앉", "시간보내", "장시간머물", "오래작업", "머물기")
            if not any(_compact(term) in compact_span for term in stay_context):
                continue
        if extraction["polarity"] == "negative" and tag_name == "분위기좋음":
            compact_span = _compact(span)
            if not any(_compact(term) in compact_span for term in ("분위기", "공간", "매장")):
                continue
        if extraction["polarity"] == "positive" and tag_name == "분위기좋음":
            compact_span = _compact(span)
            venue_context = ("분위기", "공간", "매장", "카페", "식당", "내부", "인테리어", "좌석")
            if not any(_compact(term) in compact_span for term in venue_context):
                continue
        confidence, factors = evidence_confidence(
            source="web_search", identity_score=identity["score"],
            clarity_score=extraction["clarity_score"], observed_at=observed_at,
        )
        evidences.append({
            "tag_name": tag_name, "polarity": extraction["polarity"],
            "source_url": page["url"], "source_title": title[:180],
            "evidence_summary": span, "observed_date": page.get("published_at") or None,
            "confidence": confidence, "identity": identity,
            "extraction": {**extraction, "method": "public_page_rule", "evidence_span": span},
            "confidence_factors": factors,
            "raw": {
                "channel": "public_web_page", "provider": "naver_web_discovery",
                "query": query, "result_rank": result_rank,
                "source_domain": urlsplit(page["url"]).netloc.lower(),
                "page_fetched_at": timezone.now().isoformat(),
            },
        })
    return {"identity": identity, "evidences": evidences, "error": "" if evidences else "NO_FEATURE"}


def evidence_span(text, extraction):
    terms = (
        list(extraction.get("negative_terms") or [])
        + list(extraction.get("positive_terms") or [])
        + list(extraction.get("supporting_terms") or [])
    )
    if not terms:
        return ""
    sentences = [value.strip() for value in SENTENCE_SPLIT.split(text) if value.strip()]
    for sentence in sentences:
        if "http://" in sentence.lower() or "https://" in sentence.lower():
            continue
        if any(marker in sentence for marker in RELATED_SECTION_MARKERS):
            continue
        if (
            sentence.count("#") >= 3 or "태그 취소 확인" in sentence
            or "화면 최상단으로 이동" in sentence or "NAVER 블로그" in sentence
            or "블로그 검색" in sentence
        ):
            continue
        compact_sentence = re.sub(r"\s+", "", sentence).lower()
        if any(re.sub(r"\s+", "", term).lower() in compact_sentence for term in terms):
            return sentence[:500]
    return ""


def relevant_page_text(text):
    cutoff = len(text)
    for marker in RELATED_SECTION_MARKERS:
        index = text.find(marker)
        if index >= 0:
            cutoff = min(cutoff, index)
    return text[:cutoff].strip()


def normalize_page_polarity(tag_name, span, extraction):
    compact_span = _compact(span)
    contradicting = False
    if tag_name == "무료와이파이":
        contradicting = bool(re.search(r"(?:와이파이|무선인터넷)(?:여부)?[:：]?(?:x|없|불가)", compact_span, re.I))
    elif tag_name == "데이트좋음":
        contradicting = "데이트" in compact_span and any(
            term in compact_span for term in ("비추천", "분위기는아님", "분위기가아님")
        )
    elif tag_name in {"노트북작업", "작업하기좋음"}:
        contradicting = bool(re.search(r"(?:카공|노트북|작업).{0,12}(?:아니|금지|불가|어렵)", compact_span))
    elif tag_name == "조용함" and any(
        term in compact_span for term in ("북적거림보다는한산", "북적이지않", "시끄럽지않", "아무도없")
    ):
        return {
            **extraction,
            "polarity": "positive",
            "strength": "SUPPORTING",
            "clarity_score": max(65, extraction.get("clarity_score", 0)),
        }
    elif tag_name == "혼밥좋음" and re.search(r"혼밥(?:을|해|했|하)", compact_span):
        direct_appraisal = ("혼밥하기좋", "혼밥하기편", "혼자먹기좋", "혼자먹기편", "혼자식사하기좋", "혼자식사하기편")
        if not any(term in compact_span for term in direct_appraisal):
            return {
                **extraction,
                "strength": "SUPPORTING",
                "clarity_score": min(70, extraction.get("clarity_score", 70)),
            }
    elif tag_name == "혼자이용좋음" and any(
        term in compact_span for term in ("혼자앉기보다", "혼자오기보다", "혼자방문하기보다")
    ):
        contradicting = True
    elif tag_name == "장기체류좋음" and "시간보내" in compact_span and not any(
        term in compact_span for term in ("오래", "장시간")
    ):
        return {
            **extraction,
            "strength": "SUPPORTING",
            "clarity_score": min(70, extraction.get("clarity_score", 70)),
        }
    elif tag_name == "웨이팅적음" and re.search(r"(?:기다리진않|기다리지않|대기없이|웨이팅없)", compact_span):
        return {
            **extraction,
            "polarity": "positive",
            "strength": "DIRECT",
            "clarity_score": max(85, int(extraction.get("clarity_score") or 0)),
        }
    if not contradicting:
        return extraction
    return {
        **extraction,
        "polarity": "negative",
        "strength": "CONTRADICTING",
        "clarity_score": max(80, int(extraction.get("clarity_score") or 0)),
    }


def _compact(value):
    return re.sub(r"[^0-9a-zA-Z가-힣]", "", str(value or "")).lower()


def source_type(url):
    host = urlsplit(url).netloc.lower()
    if "blog" in host or host.endswith("tistory.com"):
        return "blog"
    return "web_content"


def _published_at(meta):
    for key, value in meta.items():
        if key in META_DATE_KEYS or key.endswith("published_time") or key.endswith("datepublished"):
            value = str(value).strip()
            for candidate in (value, value[:10]):
                try:
                    return datetime.fromisoformat(candidate.replace("Z", "+00:00")).date().isoformat()
                except ValueError:
                    continue
    return None


def _fetch_result(*, error, status_code=0, content_type=""):
    return {"ok": False, "error": error, "status_code": status_code, "content_type": content_type}


def _public_post_frame(page_url, frames):
    page = urlsplit(page_url)
    for frame in frames:
        target = urljoin(page_url, frame)
        parts = urlsplit(target)
        if parts.hostname == page.hostname and parts.path.endswith("/PostView.naver"):
            safe, error = safe_public_url(target)
            if not error:
                return safe
    return ""


def _user_agent():
    return getattr(settings, "PUBLIC_PAGE_FETCH_USER_AGENT", "LifeInfraMapEvidenceBot/1.0")


def _timeout():
    return getattr(settings, "PUBLIC_PAGE_FETCH_TIMEOUT", 8)


def _max_bytes():
    return getattr(settings, "PUBLIC_PAGE_FETCH_MAX_BYTES", 1_500_000)


def _min_text_length():
    return getattr(settings, "PUBLIC_PAGE_FETCH_MIN_TEXT_LENGTH", 200)


def _max_text_length():
    return getattr(settings, "PUBLIC_PAGE_FETCH_MAX_TEXT_LENGTH", 100_000)
