# Generated by Django 6.0.5 on 2026-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailVerificationCode',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
