"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name, default, min_value=None, max_value=None):
    try:
        value = int(os.getenv(name, default))
    except (TypeError, ValueError):
        value = default

    if min_value is not None:
        value = max(value, min_value)
    if max_value is not None:
        value = min(value, max_value)
    return value


KAKAO_REST_API_KEY = os.getenv("KAKAO_REST_API_KEY")
AI_PROVIDER = os.getenv("AI_PROVIDER", "openai").strip().lower()
AI_WEB_SEARCH_ENABLED = _env_bool("AI_WEB_SEARCH_ENABLED", False)
AI_WEB_SEARCH_PROVIDER = os.getenv("AI_WEB_SEARCH_PROVIDER", "naver_search").strip().lower()
AI_WEB_SEARCH_SUMMARY_PROVIDER = os.getenv("AI_WEB_SEARCH_SUMMARY_PROVIDER", "").strip().lower()
AI_WEB_SEARCH_GROUNDING_SUPPORTED = _env_bool("AI_WEB_SEARCH_GROUNDING_SUPPORTED", False)
AI_INTENT_MODEL = os.getenv("AI_INTENT_MODEL", "gpt-5-mini")
AI_QUERY_REPAIR_MODEL = os.getenv("AI_QUERY_REPAIR_MODEL", "gpt-5-nano")
AI_RERANK_MODEL = os.getenv("AI_RERANK_MODEL", "gpt-5-nano")
AI_WEB_SEARCH_MODEL = os.getenv("AI_WEB_SEARCH_MODEL", "gpt-5-nano")
AI_WEB_SEARCH_REASONING_EFFORT = os.getenv("AI_WEB_SEARCH_REASONING_EFFORT", "").strip().lower()
AI_REASONING_EFFORT = os.getenv("AI_REASONING_EFFORT", "").strip().lower()
AI_WEB_SEARCH_MAX_CANDIDATES = _env_int("AI_WEB_SEARCH_MAX_CANDIDATES", 1, 1, 1)
AI_WEB_SEARCH_MAX_OUTPUT_TOKENS = _env_int("AI_WEB_SEARCH_MAX_OUTPUT_TOKENS", 800, 200, 800)
AI_REASON_MODEL = os.getenv("AI_REASON_MODEL", "gpt-5-nano")
GMS_MODEL = os.getenv("GMS_MODEL", AI_INTENT_MODEL)
GMS_API_KEY = os.getenv("GMS_API_KEY", "")
GMS_API_URL = os.getenv("GMS_API_URL", "")
GMS_API_BASE_URL = os.getenv("GMS_API_BASE_URL", "")
GMS_OPENAI_RESPONSES_PATH = os.getenv(
    "GMS_OPENAI_RESPONSES_PATH",
    "api.openai.com/v1/responses",
)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_API_BASE_URL = os.getenv("OPENAI_API_BASE_URL", "https://api.openai.com/v1")
IS_TESTING = "test" in sys.argv
AI_PROVIDER_CONFIGURED = (
    (
        AI_PROVIDER == "gms"
        and bool(GMS_API_KEY)
        and bool(GMS_API_URL or GMS_API_BASE_URL)
    )
    or (
        AI_PROVIDER == "openai"
        and bool(OPENAI_API_KEY)
    )
)
CONVERSATIONAL_SEARCH_AI_ENABLED = _env_bool(
    "CONVERSATIONAL_SEARCH_AI_ENABLED",
    (not IS_TESTING and AI_PROVIDER_CONFIGURED),
)
AI_SEARCH_INTENT_MAX_ATTEMPTS = _env_int("AI_SEARCH_INTENT_MAX_ATTEMPTS", 1, 1, 2)
AI_SEARCH_PRIMARY_QUERY_LIMIT = _env_int("AI_SEARCH_PRIMARY_QUERY_LIMIT", 4, 1, 5)
AI_SEARCH_KAKAO_MAX_QUERIES = _env_int("AI_SEARCH_KAKAO_MAX_QUERIES", 3, 1, 5)
AI_SEARCH_KAKAO_QUERY_SIZE = _env_int("AI_SEARCH_KAKAO_QUERY_SIZE", 15, 1, 15)
AI_SEARCH_KAKAO_RADIUS = _env_int("AI_SEARCH_KAKAO_RADIUS", 5000, 300, 20000)
AI_SEARCH_WEB_MAX_QUERIES = _env_int("AI_SEARCH_WEB_MAX_QUERIES", 2, 1, 3)
AI_SEARCH_MIN_STRONG_MEDIUM_CANDIDATES = _env_int("AI_SEARCH_MIN_STRONG_MEDIUM_CANDIDATES", 3, 0, 20)
AI_SEARCH_MIN_RESULTS = _env_int("AI_SEARCH_MIN_RESULTS", 10, 1, 20)
AI_SEARCH_RERANK_MAX_CANDIDATES = _env_int("AI_SEARCH_RERANK_MAX_CANDIDATES", 15, 5, 30)
AI_SEARCH_RERANK_MAX_COMPLETION_TOKENS = _env_int("AI_SEARCH_RERANK_MAX_COMPLETION_TOKENS", 2500, 800, 4000)
AI_REQUEST_TIMEOUT = int(os.getenv("AI_REQUEST_TIMEOUT", "20"))
AI_INTENT_TIMEOUT = _env_int("AI_INTENT_TIMEOUT", min(AI_REQUEST_TIMEOUT, 10), 3, 30)
AI_QUERY_REPAIR_TIMEOUT = _env_int("AI_QUERY_REPAIR_TIMEOUT", min(AI_REQUEST_TIMEOUT, 5), 2, 20)
AI_RERANK_TIMEOUT = _env_int("AI_RERANK_TIMEOUT", min(AI_REQUEST_TIMEOUT, 7), 2, 20)
NAVER_SEARCH_CLIENT_ID = os.getenv("NAVER_SEARCH_CLIENT_ID", "")
NAVER_SEARCH_CLIENT_SECRET = os.getenv("NAVER_SEARCH_CLIENT_SECRET", "")
NAVER_SEARCH_DISPLAY = _env_int("NAVER_SEARCH_DISPLAY", 5, 1, 100)
NAVER_SEARCH_SORT = os.getenv("NAVER_SEARCH_SORT", "sim").strip() or "sim"
AI_WEB_SEARCH_AVAILABLE = (
    AI_WEB_SEARCH_ENABLED
    and (
        (
            AI_WEB_SEARCH_PROVIDER == "gms"
            and bool(GMS_API_KEY)
            and bool(GMS_API_URL or GMS_API_BASE_URL)
        )
        or (
            AI_WEB_SEARCH_PROVIDER == "openai"
            and bool(OPENAI_API_KEY)
        )
        or AI_WEB_SEARCH_PROVIDER == "naver_search"
    )
)
AI_WEB_SEARCH_AUTO_MERGE_ENABLED = _env_bool("AI_WEB_SEARCH_AUTO_MERGE_ENABLED", AI_WEB_SEARCH_AVAILABLE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@$$oq#1_&d5ym20rfjx(c#t3f0hkyext842=2kk7nnsu8jim*$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 기존 앱들
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 외부 라이브러리
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # 로컬 앱
    'recommendations',
    'accounts',
    'boards',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# CORS 설정
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# DRF 설정
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


