"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import sys
from dotenv import load_dotenv
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def _env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def _env_int(name, default, min_value=None, max_value=None):
    try:
        value = int(os.getenv(name, default))
    except (TypeError, ValueError):
        value = default

    if min_value is not None:
        value = max(value, min_value)
    if max_value is not None:
        value = min(value, max_value)
    return value


KAKAO_REST_API_KEY = os.getenv("KAKAO_REST_API_KEY")
AI_PROVIDER = os.getenv("AI_PROVIDER", "openai").strip().lower()
AI_WEB_SEARCH_ENABLED = _env_bool("AI_WEB_SEARCH_ENABLED", False)
AI_WEB_SEARCH_PROVIDER = os.getenv("AI_WEB_SEARCH_PROVIDER", "naver_search").strip().lower()
AI_WEB_SEARCH_SUMMARY_PROVIDER = os.getenv("AI_WEB_SEARCH_SUMMARY_PROVIDER", "").strip().lower()
AI_WEB_SEARCH_GROUNDING_SUPPORTED = _env_bool("AI_WEB_SEARCH_GROUNDING_SUPPORTED", False)
AI_INTENT_MODEL = os.getenv("AI_INTENT_MODEL", "gpt-5-mini")
AI_QUERY_REPAIR_MODEL = os.getenv("AI_QUERY_REPAIR_MODEL", "gpt-5-nano")
AI_RERANK_MODEL = os.getenv("AI_RERANK_MODEL", "gpt-5-nano")
AI_WEB_SEARCH_MODEL = os.getenv("AI_WEB_SEARCH_MODEL", "gpt-5-nano")
AI_WEB_SEARCH_REASONING_EFFORT = os.getenv("AI_WEB_SEARCH_REASONING_EFFORT", "").strip().lower()
AI_REASONING_EFFORT = os.getenv("AI_REASONING_EFFORT", "").strip().lower()
AI_RERANK_REASONING_EFFORT = os.getenv("AI_RERANK_REASONING_EFFORT", "low").strip().lower()
# 인텐트 플래너도 reasoning 토큰 때문에 타임아웃이 나므로 effort를 지정한다.
AI_INTENT_REASONING_EFFORT = os.getenv("AI_INTENT_REASONING_EFFORT", "low").strip().lower()
AI_WEB_SEARCH_MAX_CANDIDATES = _env_int("AI_WEB_SEARCH_MAX_CANDIDATES", 1, 1, 1)
AI_WEB_SEARCH_MAX_OUTPUT_TOKENS = _env_int("AI_WEB_SEARCH_MAX_OUTPUT_TOKENS", 800, 200, 800)
AI_REASON_MODEL = os.getenv("AI_REASON_MODEL", "gpt-5-nano")
GMS_MODEL = os.getenv("GMS_MODEL", AI_INTENT_MODEL)
GMS_API_KEY = os.getenv("GMS_API_KEY", "")
GMS_API_URL = os.getenv("GMS_API_URL", "")
GMS_API_BASE_URL = os.getenv("GMS_API_BASE_URL", "")
GMS_OPENAI_RESPONSES_PATH = os.getenv(
    "GMS_OPENAI_RESPONSES_PATH",
    "api.openai.com/v1/responses",
)
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")
OPENAI_API_BASE_URL = os.getenv("OPENAI_API_BASE_URL", "https://api.openai.com/v1")
IS_TESTING = "test" in sys.argv
AI_PROVIDER_CONFIGURED = (
    (
        AI_PROVIDER == "gms"
        and bool(GMS_API_KEY)
        and bool(GMS_API_URL or GMS_API_BASE_URL)
    )
    or (
        AI_PROVIDER == "openai"
        and bool(OPENAI_API_KEY)
    )
)
CONVERSATIONAL_SEARCH_AI_ENABLED = _env_bool(
    "CONVERSATIONAL_SEARCH_AI_ENABLED",
    (not IS_TESTING and AI_PROVIDER_CONFIGURED),
)
AI_SEARCH_INTENT_MAX_ATTEMPTS = _env_int("AI_SEARCH_INTENT_MAX_ATTEMPTS", 1, 1, 2)
AI_SEARCH_PRIMARY_QUERY_LIMIT = _env_int("AI_SEARCH_PRIMARY_QUERY_LIMIT", 4, 1, 5)
AI_SEARCH_KAKAO_MAX_QUERIES = _env_int("AI_SEARCH_KAKAO_MAX_QUERIES", 3, 1, 5)
AI_SEARCH_KAKAO_QUERY_SIZE = _env_int("AI_SEARCH_KAKAO_QUERY_SIZE", 15, 1, 15)
AI_SEARCH_KAKAO_RADIUS = _env_int("AI_SEARCH_KAKAO_RADIUS", 5000, 300, 20000)
AI_SEARCH_WEB_MAX_QUERIES = _env_int("AI_SEARCH_WEB_MAX_QUERIES", 2, 1, 3)
AI_SEARCH_MIN_STRONG_MEDIUM_CANDIDATES = _env_int("AI_SEARCH_MIN_STRONG_MEDIUM_CANDIDATES", 3, 0, 20)
AI_SEARCH_MIN_RESULTS = _env_int("AI_SEARCH_MIN_RESULTS", 10, 1, 20)
AI_SEARCH_RERANK_MAX_CANDIDATES = _env_int("AI_SEARCH_RERANK_MAX_CANDIDATES", 8, 5, 30)
AI_SEARCH_RERANK_MAX_COMPLETION_TOKENS = _env_int("AI_SEARCH_RERANK_MAX_COMPLETION_TOKENS", 2500, 800, 4000)
# 같은 후보 묶음에 대한 AI 판정 재사용 시간(초). 0이면 캐시하지 않는다.
# 테스트는 각 케이스가 실제 호출 경로를 그대로 타야 하므로 캐시를 쓰지 않는다.
AI_RERANK_CACHE_TTL = _env_int("AI_RERANK_CACHE_TTL", 0 if IS_TESTING else 900, 0, 86400)
# 화장실/주차장처럼 카테고리와 거리로 답이 정해지는 요청에서 AI 후보 평가를 건너뛴다.
AI_SEARCH_ROUTE_CATEGORY_REQUESTS = _env_bool("AI_SEARCH_ROUTE_CATEGORY_REQUESTS", True)
AI_REQUEST_TIMEOUT = int(os.getenv("AI_REQUEST_TIMEOUT", "20"))
AI_INTENT_TIMEOUT = _env_int("AI_INTENT_TIMEOUT", min(AI_REQUEST_TIMEOUT, 10), 3, 30)
AI_QUERY_REPAIR_TIMEOUT = _env_int("AI_QUERY_REPAIR_TIMEOUT", min(AI_REQUEST_TIMEOUT, 5), 2, 20)
AI_RERANK_TIMEOUT = _env_int("AI_RERANK_TIMEOUT", max(AI_REQUEST_TIMEOUT, 20), 2, 40)
NAVER_SEARCH_CLIENT_ID = os.getenv("NAVER_SEARCH_CLIENT_ID", "")
NAVER_SEARCH_CLIENT_SECRET = os.getenv("NAVER_SEARCH_CLIENT_SECRET", "")
NAVER_SEARCH_DISPLAY = _env_int("NAVER_SEARCH_DISPLAY", 5, 1, 100)
NAVER_SEARCH_SORT = os.getenv("NAVER_SEARCH_SORT", "sim").strip() or "sim"
AI_WEB_SEARCH_AVAILABLE = (
    AI_WEB_SEARCH_ENABLED
    and (
        (
            AI_WEB_SEARCH_PROVIDER == "gms"
            and bool(GMS_API_KEY)
            and bool(GMS_API_URL or GMS_API_BASE_URL)
        )
        or (
            AI_WEB_SEARCH_PROVIDER == "openai"
            and bool(OPENAI_API_KEY)
        )
        or AI_WEB_SEARCH_PROVIDER == "naver_search"
    )
)
AI_WEB_SEARCH_AUTO_MERGE_ENABLED = _env_bool("AI_WEB_SEARCH_AUTO_MERGE_ENABLED", AI_WEB_SEARCH_AVAILABLE)

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@$$oq#1_&d5ym20rfjx(c#t3f0hkyext842=2kk7nnsu8jim*$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    # 기존 앱들
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 외부 라이브러리
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # 로컬 앱
    'recommendations',
    'accounts',
    'boards',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DB_ENGINE 이 `postgres` 면 Postgres, 아니면 기존 SQLite 를 씁니다.
# 전환 중에도 양쪽을 오갈 수 있도록 기본값은 SQLite 로 둡니다.
DB_ENGINE = os.getenv("DB_ENGINE", "sqlite").strip().lower()

if DB_ENGINE in {"postgres", "postgresql"}:
    DATABASES = {
        "default": {
            # PostGIS 질의로 넘어가면 django.contrib.gis.db.backends.postgis 로 바꿉니다.
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB", "life_infra_map"),
            "USER": os.getenv("POSTGRES_USER", "life_infra_map"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "life_infra_map"),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.getenv("POSTGRES_PORT", "5432"),
            # 요청마다 연결을 새로 맺지 않도록 재사용합니다.
            "CONN_MAX_AGE": _env_int("DB_CONN_MAX_AGE", 60, 0, 600),
            "OPTIONS": {
                "connect_timeout": _env_int("DB_CONNECT_TIMEOUT", 5, 1, 30),
            },
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }

# SQLite -> Postgres 이관용 읽기 전용 연결입니다.
# `migrate_sqlite_to_postgres` 커맨드가 이 별칭에서 읽습니다. 이관이 끝나면 지워도 됩니다.
LEGACY_SQLITE_PATH = os.getenv("LEGACY_SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))
if DB_ENGINE in {"postgres", "postgresql"} and os.path.exists(LEGACY_SQLITE_PATH):
    DATABASES["legacy_sqlite"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": LEGACY_SQLITE_PATH,
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# 업로드 파일 저장 위치입니다.
# `local` 은 기존처럼 backend/media/ 에 두고, `s3` 는 S3 호환 저장소(MinIO/AWS S3)에 둡니다.
# 배포하면 컨테이너 재시작마다 로컬 파일이 사라지므로 s3 를 씁니다.
FILE_STORAGE_BACKEND = os.getenv("FILE_STORAGE_BACKEND", "local").strip().lower()

# 테스트는 저장소 컨테이너가 떠 있는지에 좌우되면 안 되고,
# 실행할 때마다 버킷에 파일을 남겨서도 안 됩니다.
if IS_TESTING:
    FILE_STORAGE_BACKEND = "local"

if FILE_STORAGE_BACKEND == "s3":
    AWS_ACCESS_KEY_ID = os.getenv("S3_ACCESS_KEY", "")
    AWS_SECRET_ACCESS_KEY = os.getenv("S3_SECRET_KEY", "")
    AWS_STORAGE_BUCKET_NAME = os.getenv("S3_BUCKET", "life-infra-map-media")
    AWS_S3_REGION_NAME = os.getenv("S3_REGION", "us-east-1")
    # MinIO 를 쓸 때만 지정합니다. 실제 AWS S3 로 가면 비워 두면 됩니다.
    AWS_S3_ENDPOINT_URL = os.getenv("S3_ENDPOINT_URL", "") or None
    # 브라우저가 접근할 주소입니다. 컨테이너 내부 주소와 다를 수 있어 따로 둡니다.
    AWS_S3_CUSTOM_DOMAIN = os.getenv("S3_PUBLIC_DOMAIN", "") or None
    # 로컬 MinIO 는 http 이고 배포 S3 는 https 입니다.
    AWS_S3_URL_PROTOCOL = os.getenv("S3_URL_PROTOCOL", "https:").strip()
    AWS_QUERYSTRING_AUTH = _env_bool("S3_QUERYSTRING_AUTH", False)
    AWS_S3_FILE_OVERWRITE = False
    AWS_DEFAULT_ACL = None
    # MinIO 는 가상 호스트 방식 주소를 기본 지원하지 않습니다.
    AWS_S3_ADDRESSING_STYLE = os.getenv("S3_ADDRESSING_STYLE", "path")

    STORAGES = {
        "default": {"BACKEND": "storages.backends.s3.S3Storage"},
        "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
    }

# CORS 설정
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]

# DRF 설정
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Spring 서비스가 발급한 토큰을 먼저 확인하고, 아니면 기존 방식으로 넘어갑니다.
        'accounts.authentication.SharedJWTAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# Spring 서비스와 공유하는 토큰 설정입니다.
# `spring-api` 의 app.jwt.secret 과 같은 값이어야 서로 발급한 토큰을 검증할 수 있습니다.
JWT_SECRET = os.getenv("JWT_SECRET", "")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
JWT_ACCESS_MINUTES = _env_int("JWT_ACCESS_MINUTES", 120, 5, 1440)

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


