# Generated by Django 6.0.5 on 2026-06-22 07:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_report'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='내용')),
                ('status', models.CharField(choices=[('pending', '답변 대기'), ('answered', '답변 완료'), ('closed', '종료')], default='pending', max_length=20, verbose_name='상태')),
                ('admin_reply', models.TextField(blank=True, verbose_name='관리자 답변')),
                ('replied_at', models.DateTimeField(blank=True, null=True, verbose_name='답변일')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('report_passed', '신고 패스'), ('report_penalty', '신고 조치'), ('admin_warning', '관리자 경고'), ('inquiry_answered', '문의 답변'), ('penalty_notice', '제재 안내'), ('system', '시스템')], default='system', max_length=30, verbose_name='알림 종류')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('penalty_type', models.CharField(choices=[('warning', '경고'), ('suspend_3_days', '3일 활동정지'), ('suspend_7_days', '7일 활동정지'), ('suspend_30_days', '30일 활동정지'), ('suspend_1_year', '1년 사용정지'), ('permanent_ban', '영구밴')], max_length=30, verbose_name='제재 종류')),
                ('reason', models.TextField(verbose_name='제재 사유')),
                ('start_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작일')),
                ('end_at', models.DateTimeField(blank=True, null=True, verbose_name='종료일')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='report',
            name='report_has_exactly_one_target',
        ),
        migrations.AddField(
            model_name='report',
            name='admin_memo',
            field=models.TextField(blank=True, verbose_name='관리자 메모'),
        ),
        migrations.AddField(
            model_name='report',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='처리일'),
        ),
        migrations.AddField(
            model_name='report',
            name='processed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_reports', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자'),
        ),
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', '대기'), ('passed', '패스'), ('penalized', '패널티 조치')], default='pending', max_length=20, verbose_name='처리 상태'),
        ),
        migrations.AlterField(
            model_name='report',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='boards.comment', verbose_name='신고 댓글'),
        ),
        migrations.AlterField(
            model_name='report',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='boards.post', verbose_name='신고 게시글'),
        ),
        migrations.AddConstraint(
            model_name='report',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('comment__isnull', True), ('post__isnull', False)), models.Q(('comment__isnull', False), ('post__isnull', True)), models.Q(('comment__isnull', True), ('post__isnull', True), ('status', 'penalized')), _connector='OR'), name='report_has_exactly_one_target'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='replied_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_inquiries', to=settings.AUTH_USER_MODEL, verbose_name='답변 관리자'),
        ),
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='발신자'),
        ),
        migrations.AddField(
            model_name='userpenalty',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_penalties', to=settings.AUTH_USER_MODEL, verbose_name='처리 관리자'),
        ),
        migrations.AddField(
            model_name='userpenalty',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL, verbose_name='제재 대상'),
        ),
    ]
