# Generated by Codex on 2026-06-23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0004_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("post_commented", "게시글 댓글"),
                    ("post_liked", "게시글 좋아요"),
                    ("comment_liked", "댓글 좋아요"),
                    ("report_passed", "신고 패스"),
                    ("report_penalty", "신고 조치"),
                    ("admin_warning", "관리자 경고"),
                    ("inquiry_answered", "문의 답변"),
                    ("penalty_notice", "제재 안내"),
                    ("system", "시스템"),
                ],
                default="system",
                max_length=30,
                verbose_name="알림 종류",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="boards.comment",
                verbose_name="대상 댓글",
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="target_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="boards.post",
                verbose_name="대상 게시글",
            ),
        ),
    ]
