# Generated by Codex on 2026-06-23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boards", "0006_comment_parent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="author_hearted",
            field=models.BooleanField(default=False, verbose_name="글쓴이 하트 여부"),
        ),
        migrations.CreateModel(
            name="CommentDislike",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="싫어요 날짜")),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_dislikes",
                        to="boards.comment",
                        verbose_name="댓글",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comment_dislikes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="commentdislike",
            constraint=models.UniqueConstraint(
                fields=("comment", "user"),
                name="unique_comment_dislike",
            ),
        ),
    ]
