# Generated by Django 6.0.5 on 2026-06-12 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('tag_type', models.CharField(choices=[('category', '카테고리'), ('recommendation', '추천가치'), ('warning', '주의/확인필요')], default='recommendation', max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('source', models.CharField(max_length=50)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('source_name', models.CharField(blank=True, max_length=100)),
                ('source_updated_at', models.DateField(blank=True, null=True)),
                ('detail_location', models.CharField(blank=True, max_length=255)),
                ('data_quality_status', models.CharField(default='candidate', max_length=30)),
                ('data_quality_score', models.IntegerField(default=50)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_place_source_external_id')],
            },
        ),
        migrations.CreateModel(
            name='PlaceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('category_rule', '카테고리 기반 기본 태그'), ('field_rule', '원본 필드 기반 태그'), ('keyword_rule', '키워드 규칙 기반 태그'), ('blog_search', '블로그 검색 기반 후보 태그'), ('external_api', '외부 API 기반 태그'), ('external_data', '외부 데이터 기반 태그'), ('ai_suggested', 'AI 추천 후보 태그'), ('checked', '검수 완료 태그'), ('user_verified', '사용자 검증 태그'), ('warning_tags', '확인 필요 태그')], default='external_data', max_length=50)),
                ('status', models.CharField(choices=[('confirmed', '확인됨'), ('candidate', '후보'), ('needs_verification', '확인 필요'), ('rejected', '반려')], default='candidate', max_length=30)),
                ('confidence', models.IntegerField(default=50)),
                ('evidence', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_tags', to='recommendations.place')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_tags', to='recommendations.tag')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('place', 'tag', 'source'), name='unique_place_tag_source')],
            },
        ),
    ]
