# Generated by Codex on 2026-06-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["category", "lat", "lng"],
                name="recommendat_categor_5e9f0d_idx",
            ),
        ),
    ]
