# Generated by Django 6.0.5 on 2026-05-20 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='raw',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
