# Generated by Django 6.0.5 on 2026-06-22 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_place_category_lat_lng_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='place',
            new_name='recommendat_categor_b22b2a_idx',
            old_name='recommendat_categor_5e9f0d_idx',
        ),
    ]
