# Generated by Django 6.0.5 on 2026-06-23 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_rename_recommendat_categor_5e9f0d_idx_recommendat_categor_b22b2a_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('search_mode', models.CharField(blank=True, max_length=50)),
                ('scenario', models.CharField(blank=True, max_length=50)),
                ('location_hint', models.CharField(blank=True, max_length=100)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('target_query', models.CharField(blank=True, max_length=255)),
                ('category_hint', models.CharField(blank=True, max_length=50)),
                ('requested_conditions', models.JSONField(blank=True, default=list)),
                ('menu_keywords', models.JSONField(blank=True, default=list)),
                ('place_type_keywords', models.JSONField(blank=True, default=list)),
                ('preferred_tags', models.JSONField(blank=True, default=list)),
                ('negative_tags', models.JSONField(blank=True, default=list)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('db_result_count', models.PositiveIntegerField(default=0)),
                ('kakao_result_count', models.PositiveIntegerField(default=0)),
                ('ai_web_result_count', models.PositiveIntegerField(default=0)),
                ('search_plan_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-created_at'], name='recommendat_user_id_5e2f42_idx'), models.Index(fields=['scenario'], name='recommendat_scenari_0d156c_idx'), models.Index(fields=['category_hint'], name='recommendat_categor_25eacc_idx')],
            },
        ),
    ]
