# Generated by Django 6.0.5 on 2026-06-23 05:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0004_usersearchlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preference_type', models.CharField(max_length=30)),
                ('key', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('score', models.FloatField(default=0)),
                ('search_count', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(default='search_log', max_length=30)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-score'], name='recommendat_user_id_f02daa_idx'), models.Index(fields=['preference_type', 'key'], name='recommendat_prefere_41c940_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'preference_type', 'key'), name='unique_user_preference')],
            },
        ),
    ]
