# Generated by Django 6.0.5 on 2026-06-23 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0005_userpreference'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('new_place', '장소 추가 제보'), ('edit_place', '장소 정보 수정 제보'), ('tag_suggestion', '태그 추가 제보'), ('wrong_info', '잘못된 정보 제보')], max_length=30)),
                ('status', models.CharField(choices=[('pending', '검토 대기'), ('approved', '승인'), ('rejected', '반려')], default='pending', max_length=20)),
                ('suggested_name', models.CharField(blank=True, max_length=255)),
                ('suggested_category', models.CharField(blank=True, max_length=50)),
                ('suggested_address', models.CharField(blank=True, max_length=255)),
                ('suggested_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('suggested_tags', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='recommendations.place')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_place_reports', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlaceReportImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='place_reports/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='recommendations.placereport')),
            ],
        ),
        migrations.AddIndex(
            model_name='placereport',
            index=models.Index(fields=['user', '-created_at'], name='recommendat_user_id_ec16bc_idx'),
        ),
        migrations.AddIndex(
            model_name='placereport',
            index=models.Index(fields=['status', '-created_at'], name='recommendat_status_56ef1b_idx'),
        ),
        migrations.AddIndex(
            model_name='placereport',
            index=models.Index(fields=['report_type'], name='recommendat_report__77e17c_idx'),
        ),
    ]
