# Generated by Django 6.0.5 on 2026-07-05 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0006_placereport_placereportimage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSavedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_key', models.CharField(max_length=255)),
                ('source', models.CharField(choices=[('local_db', '저장 장소'), ('kakao', '카카오 장소'), ('web', '웹 참고'), ('other', '기타')], default='local_db', max_length=30)),
                ('external_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('detail_url', models.URLField(blank=True, max_length=500)),
                ('kakao_place_url', models.URLField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('memo', models.TextField(blank=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_by_users', to='recommendations.place')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_places', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', '-updated_at'], name='recommendat_user_id_a14c2e_idx'), models.Index(fields=['user', 'source'], name='recommendat_user_id_f302cc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'place_key'), name='unique_user_saved_place_key')],
            },
        ),
    ]
