# Generated by Django 6.0.5 on 2026-08-11 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0007_usersavedplace'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='place',
            index=models.Index(fields=['lat', 'lng'], name='recommendat_lat_4407f8_idx'),
        ),
    ]
