# Generated by Django 6.0.5 on 2026-08-14 03:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0009_place_geography_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceSyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('dataset', models.CharField(max_length=100)),
                ('sync_type', models.CharField(choices=[('full', 'Full snapshot'), ('delta', 'Delta')], default='full', max_length=20)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='running', max_length=20)),
                ('source_uri', models.TextField(blank=True)),
                ('source_checksum', models.CharField(blank=True, max_length=64)),
                ('cursor', models.JSONField(blank=True, default=dict)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'dataset', '-started_at'], name='recommendat_source_ec6089_idx'), models.Index(fields=['status', '-started_at'], name='recommendat_status_3104cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlaceCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrative_code', models.CharField(max_length=30)),
                ('sido_name', models.CharField(blank=True, max_length=50)),
                ('sigungu_name', models.CharField(blank=True, max_length=80)),
                ('category', models.CharField(max_length=100)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('source_record_count', models.PositiveIntegerField(default=0)),
                ('active_record_count', models.PositiveIntegerField(default=0)),
                ('normalized_place_count', models.PositiveIntegerField(default=0)),
                ('tagged_place_count', models.PositiveIntegerField(default=0)),
                ('evidence_place_count', models.PositiveIntegerField(default=0)),
                ('coverage_score', models.FloatField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['sido_name', 'sigungu_name', 'category'], name='recommendat_sido_na_780b95_idx'), models.Index(fields=['coverage_score'], name='recommendat_coverag_0e9d53_idx')],
                'constraints': [models.UniqueConstraint(fields=('administrative_code', 'category', 'source'), name='unique_place_coverage_cell')],
            },
        ),
        migrations.CreateModel(
            name='PlaceTagEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('source_reference', models.CharField(blank=True, max_length=500)),
                ('polarity', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral')], default='positive', max_length=20)),
                ('confidence', models.PositiveSmallIntegerField(default=50)),
                ('evidence', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('observed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_evidence', to='recommendations.place')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_evidence', to='recommendations.tag')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_tag_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['place', 'tag', 'polarity'], name='recommendat_place_i_f1b132_idx'), models.Index(fields=['source', '-observed_at'], name='recommendat_source_f21102_idx'), models.Index(fields=['expires_at'], name='recommendat_expires_16dbd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='SourcePlaceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50)),
                ('dataset', models.CharField(max_length=100)),
                ('source_record_id', models.CharField(max_length=160)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('business_type', models.CharField(blank=True, max_length=100)),
                ('business_status', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('road_address', models.CharField(blank=True, max_length=500)),
                ('sido_name', models.CharField(blank=True, max_length=50)),
                ('sigungu_name', models.CharField(blank=True, max_length=80)),
                ('administrative_code', models.CharField(blank=True, max_length=30)),
                ('source_x', models.CharField(blank=True, max_length=50)),
                ('source_y', models.CharField(blank=True, max_length=50)),
                ('coordinate_reference_system', models.CharField(blank=True, max_length=30)),
                ('license_date', models.DateField(blank=True, null=True)),
                ('closed_date', models.DateField(blank=True, null=True)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('normalized_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_records', to='recommendations.place')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'dataset', 'is_active'], name='recommendat_source_72853c_idx'), models.Index(fields=['sido_name', 'sigungu_name', 'category'], name='recommendat_sido_na_abcd43_idx'), models.Index(fields=['normalized_place'], name='recommendat_normali_249134_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'dataset', 'source_record_id'), name='unique_source_place_record')],
            },
        ),
    ]
