# Generated by Django 6.0.5 on 2026-08-14 07:28

import django.db.models.deletion
import recommendations.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0011_placetagevidence_evidence_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceInteractionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_key', models.CharField(default=recommendations.models.new_evidence_key, editable=False, max_length=64, unique=True)),
                ('session_key', models.CharField(blank=True, max_length=64)),
                ('search_id', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(choices=[('search', 'Search demand'), ('clarification', 'Clarification answer'), ('impression', 'Result impression'), ('click', 'Result click'), ('save', 'Place save'), ('dismiss', 'Result rejection'), ('tag_confirm', 'Tag confirmed'), ('tag_reject', 'Tag rejected')], max_length=30)),
                ('place_key', models.CharField(blank=True, max_length=255)),
                ('place_source', models.CharField(blank=True, max_length=50)),
                ('place_external_id', models.CharField(blank=True, max_length=100)),
                ('place_name', models.CharField(blank=True, max_length=200)),
                ('place_category', models.CharField(blank=True, max_length=100)),
                ('query', models.CharField(blank=True, max_length=255)),
                ('requested_tags', models.JSONField(blank=True, default=list)),
                ('tag_name', models.CharField(blank=True, max_length=50)),
                ('position', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interaction_events', to='recommendations.place')),
                ('search_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='recommendations.usersearchlog')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_interactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['search_id', 'event_type'], name='recommendat_search__2515e5_idx'), models.Index(fields=['place', 'event_type', '-created_at'], name='recommendat_place_i_47f10f_idx'), models.Index(fields=['tag_name', 'event_type', '-created_at'], name='recommendat_tag_nam_3001ec_idx'), models.Index(fields=['session_key', '-created_at'], name='recommendat_session_95e323_idx')],
            },
        ),
    ]
