# Generated by Django 6.0.5 on 2026-08-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0012_placeinteractionevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placetag',
            name='source',
            field=models.CharField(choices=[('category_rule', '카테고리 기반 기본 태그'), ('field_rule', '원본 필드 기반 태그'), ('keyword_rule', '키워드 규칙 기반 태그'), ('blog_search', '블로그 검색 기반 후보 태그'), ('external_api', '외부 API 기반 태그'), ('external_data', '외부 데이터 기반 태그'), ('ai_suggested', 'AI 추천 후보 태그'), ('checked', '검수 완료 태그'), ('user_verified', '사용자 검증 태그'), ('interaction_signal', '검색 행동 기반 후보 태그'), ('warning_tags', '확인 필요 태그')], default='external_data', max_length=50),
        ),
    ]
