# Generated by Django 6.0.5 on 2026-08-14 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0013_alter_placetag_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagEnrichmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('demand_count', models.PositiveIntegerField(default=1)),
                ('source_query', models.CharField(blank=True, max_length=255)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('last_requested_at', models.DateTimeField(auto_now=True)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_enrichment_requests', to='recommendations.place')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-priority', 'created_at'], name='recommendat_status_39660e_idx'), models.Index(fields=['tag_name', 'status'], name='recommendat_tag_nam_3760d8_idx')],
                'constraints': [models.UniqueConstraint(fields=('place', 'tag_name'), name='unique_place_tag_enrichment_request')],
            },
        ),
    ]
