# Generated by Django 6.0.5 on 2026-08-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0014_tag_enrichment_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='KakaoPlaceSearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_hash', models.CharField(max_length=64, unique=True)),
                ('query', models.CharField(max_length=500)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('radius', models.PositiveIntegerField(default=3000)),
                ('response', models.JSONField(blank=True, default=dict)),
                ('result_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at'], name='recommendat_expires_d8fb69_idx')],
            },
        ),
        migrations.CreateModel(
            name='KakaoPlaceMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('ambiguous', 'Ambiguous'), ('unmatched', 'Unmatched'), ('error', 'Error')], default='pending', max_length=20)),
                ('kakao_place_id', models.CharField(blank=True, max_length=100)),
                ('score', models.FloatField(default=0)),
                ('score_margin', models.FloatField(default=0)),
                ('distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('query', models.CharField(blank=True, max_length=500)),
                ('score_details', models.JSONField(blank=True, default=dict)),
                ('candidates', models.JSONField(blank=True, default=list)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('matched_at', models.DateTimeField(blank=True, null=True)),
                ('last_attempted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canonical_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kakao_source_matches', to='recommendations.place')),
                ('source_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kakao_match', to='recommendations.sourceplacerecord')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'source_record'], name='recommendat_status_1fb629_idx'), models.Index(fields=['kakao_place_id'], name='recommendat_kakao_p_c823a3_idx'), models.Index(fields=['-last_attempted_at'], name='recommendat_last_at_3b8ce0_idx')],
            },
        ),
    ]
