# Generated by Django 6.0.5 on 2026-08-15 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0015_kakaoplacesearchcache_kakaoplacematch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderQuotaUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('usage_date', models.DateField()),
                ('daily_limit', models.PositiveIntegerField(default=25000)),
                ('reserved_count', models.PositiveIntegerField(default=0)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('success_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('rate_limited_count', models.PositiveIntegerField(default=0)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['usage_date', 'provider'], name='recommendat_usage_d_319fe9_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'usage_date'), name='unique_provider_daily_quota_usage')],
            },
        ),
        migrations.CreateModel(
            name='PlaceTagCollectionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='naver_search', max_length=50)),
                ('cycle_date', models.DateField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('retry', 'Retry'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('priority', models.PositiveIntegerField(default=1)),
                ('requested_tags', models.JSONField(blank=True, default=list)),
                ('planned_requests', models.PositiveSmallIntegerField(default=1)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('worker_id', models.CharField(blank=True, max_length=100)),
                ('error_code', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_collection_jobs', to='recommendations.place')),
            ],
            options={
                'indexes': [models.Index(fields=['status', '-priority', 'created_at'], name='recommendat_status_0e1559_idx'), models.Index(fields=['provider', 'cycle_date', 'status'], name='recommendat_provide_26878a_idx'), models.Index(fields=['place', '-cycle_date'], name='recommendat_place_i_c5140a_idx')],
                'constraints': [models.UniqueConstraint(fields=('place', 'provider', 'cycle_date'), name='unique_daily_place_tag_collection_job')],
            },
        ),
    ]
