# Generated by Django 6.0.5 on 2026-08-17 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0021_dashboard_growth_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='placefeaturedocument',
            name='embedding_source_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='placefeaturedocument',
            name='embedding_strategy',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
