# Generated by Django 6.0.5 on 2026-08-23 10:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0022_placefeaturedocument_embedding_source_hash_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('anonymous_token_hash', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed')], default='active', max_length=20)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('state', models.JSONField(blank=True, default=dict)),
                ('version', models.PositiveIntegerField(default=0)),
                ('turn_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='place_conversation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationTurn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('user_query', models.TextField()),
                ('action', models.CharField(blank=True, max_length=40)),
                ('assistant_message', models.TextField(blank=True)),
                ('state_before', models.JSONField(blank=True, default=dict)),
                ('state_after', models.JSONField(blank=True, default=dict)),
                ('result_refs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='recommendations.conversationsession')),
            ],
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['user', '-updated_at'], name='recommendat_user_id_32fb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationsession',
            index=models.Index(fields=['status', '-updated_at'], name='recommendat_status_ea64b4_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationturn',
            index=models.Index(fields=['session', 'sequence'], name='recommendat_session_f6e27f_idx'),
        ),
        migrations.AddConstraint(
            model_name='conversationturn',
            constraint=models.UniqueConstraint(fields=('session', 'sequence'), name='unique_conversation_turn_sequence'),
        ),
    ]
