# Generated by Django 6.0.5 on 2026-09-08 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0023_conversationsession_conversationturn_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', '확인 필요'), ('approved', '검토 승인'), ('rejected', '반려'), ('research', '재조사 필요')], db_index=True, default='pending', max_length=24)),
                ('note', models.TextField(blank=True)),
                ('history', models.JSONField(default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='recommendations.placetagevidence')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
