# Generated by Django 6.0.5 on 2026-09-08 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0024_evidence_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_key', models.CharField(max_length=240, unique=True)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
        ),
    ]
